import asyncHandler from 'express-async-handler';
import Prescription from '../models/Prescription.js';
import Patient from '../models/Patient.js';
import Doctor from '../models/Doctor.js';
import Medicine from '../models/Medicine.js';
import Notification from '../models/Notification.js';
import User from '../models/User.js';
import { sendSms } from '../services/twilioService.js';
import Appointment from '../models/Appointment.js'; // Import Appointment model for patient filtering
import pdf from 'html-pdf'; // Import html-pdf library

// Function to generate PDF content (HTML string)
const generatePrescriptionHtml = (prescription) => {
  // Basic styling for the PDF. You can expand this with more complex CSS.
  const styles = `
    <style>
      body { font-family: 'Helvetica Neue', 'Helvetica', Arial, sans-serif; margin: 20px; color: #333; }
      .container { width: 100%; max-width: 800px; margin: 0 auto; border: 1px solid #eee; padding: 30px; box-shadow: 0 0 10px rgba(0,0,0,0.05); }
      .header { text-align: center; margin-bottom: 30px; border-bottom: 1px solid #eee; padding-bottom: 20px; }
      .header h1 { color: #0096C7; margin: 0; font-size: 28px; }
      .header p { color: #777; font-size: 14px; margin-top: 5px; }
      .section-title { color: #0096C7; border-bottom: 2px solid #0096C7; padding-bottom: 5px; margin-top: 25px; margin-bottom: 15px; font-size: 20px; }
      .info-grid { display: flex; flex-wrap: wrap; margin-bottom: 20px; }
      .info-item { flex: 1 1 48%; margin-bottom: 15px; }
      .info-item label { font-weight: bold; color: #555; display: block; margin-bottom: 3px; font-size: 13px; }
      .info-item span { font-size: 15px; color: #333; }
      table { width: 100%; border-collapse: collapse; margin-top: 20px; }
      th, td { border: 1px solid #eee; padding: 12px; text-align: left; font-size: 14px; }
      th { background-color: #f9f9f9; color: #555; font-weight: bold; }
      .notes { background-color: #f9f9f9; padding: 15px; border-radius: 8px; margin-top: 30px; font-size: 14px; line-height: 1.6; color: #555; }
      .footer { text-align: center; margin-top: 40px; font-size: 12px; color: #aaa; }
    </style>
  `;

  const medicinesTableRows = prescription.medicines.map(med => `
    <tr>
      <td>${med.name || med.medicine?.brandName || med.medicine?.genericName || 'N/A'}</td>
      <td>${med.dosage || 'N/A'}</td>
      <td>${med.frequency || 'N/A'}</td>
      <td>${med.duration || 'N/A'}</td>
    </tr>
  `).join('');

  return `
    <html>
    <head>
      <title>Prescription #${prescription.prescriptionId}</title>
      ${styles}
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>HealthSphere</h1>
          <p>Your Health, Our Priority</p>
        </div>

        <h2 class="section-title">Prescription Details</h2>

        <div class="info-grid">
          <div class="info-item">
            <label>Prescription ID:</label>
            <span>${prescription.prescriptionId || 'N/A'}</span>
          </div>
          <div class="info-item">
            <label>Date of Issue:</label>
            <span>${new Date(prescription.issueDate).toLocaleDateString() || 'N/A'}</span>
          </div>
          <div class="info-item">
            <label>Prescribed by:</label>
            <span>Dr. ${prescription.doctor?.user?.name || 'N/A'} (${prescription.doctor?.specialty || 'N/A'})</span>
          </div>
          <div class="info-item">
            <label>For Patient:</label>
            <span>${prescription.patient?.user?.name || 'N/A'}</span>
          </div>
        </div>

        <h2 class="section-title">Medicines</h2>
        <table>
          <thead>
            <tr>
              <th>Medicine</th>
              <th>Dosage</th>
              <th>Frequency</th>
              <th>Duration</th>
            </tr>
          </thead>
          <tbody>
            ${medicinesTableRows}
          </tbody>
        </table>

        <div class="notes">
          <h4>Doctor's Notes:</h4>
          <p>${prescription.notes || 'No notes provided.'}</p>
        </div>

        <div class="footer">
          <p>Generated by HealthSphere on ${new Date().toLocaleDateString()}</p>
        </div>
      </div>
    </body>
    </html>
  `;
};

// @desc    Get all prescriptions (Admin) or prescriptions issued by a specific doctor (Doctor)
// @route   GET /api/prescriptions
// @access  Private/Admin or Doctor
const getPrescriptionsForDoctor = asyncHandler(async (req, res) => {
  let query = {};

  if (req.user.role === 'Doctor') {
      const doctor = await Doctor.findOne({ user: req.user._id });
      if (!doctor) {
          res.status(404);
          throw new Error('Doctor profile not found');
      }
      query = { doctor: doctor._id };
  }

  const prescriptions = await Prescription.find(query)
    .populate('patient', 'patientId user')
    .populate('doctor', 'specialty user')
    .populate('medicines.medicine', 'brandName genericName strength');

  res.json(prescriptions);
});

// @desc    Get patient specific prescriptions (Patient, Admin, Doctor)
// @route   GET /api/prescriptions/patient/:patientId
// @access  Private/Patient, Admin or Doctor
const getPatientPrescriptions = asyncHandler(async (req, res) => {
    const patient = await Patient.findOne({ user: req.user._id });

    if (!patient) {
        res.status(404);
        throw new Error('Patient profile not found for this user');
    }

    const prescriptions = await Prescription.find({ patient: patient._id })
      .populate({ path: 'patient', select: 'patientId dob user', populate: { path: 'user', select: 'name' } })
      .populate({ path: 'doctor', select: 'specialty user', populate: { path: 'user', select: 'name' } })
      .populate({ 
            path: 'medicines.medicine',
            select: 'brandName genericName strength',
            strictPopulate: false
      });

    res.json(prescriptions);
});

// @desc    Get single prescription by ID
// @route   GET /api/prescriptions/:id
// @access  Private/Admin, Doctor or Patient
const getPrescriptionById = asyncHandler(async (req, res) => {
  const prescription = await Prescription.findById(req.params.id)
    .populate({ path: 'patient', select: 'patientId dob user', populate: { path: 'user', select: 'name' } })
    .populate({ path: 'doctor', select: 'specialty user', populate: { path: 'user', select: 'name' } })
    .populate('medicines.medicine', 'brandName genericName strength');

  if (prescription) {
    // Authorization: Only admin, the patient, or the prescribing doctor can view
    const isAuthorized = req.user.role === 'Admin' ||
                         (prescription.patient && prescription.patient.user && prescription.patient.user.toString() === req.user._id.toString()) ||
                         (prescription.doctor && prescription.doctor.user && prescription.doctor.user.toString() === req.user._id.toString());

    if (!isAuthorized) {
        res.status(403);
        throw new Error('Not authorized to view this prescription');
    }

    res.json(prescription);
  } else {
    res.status(404);
    throw new Error('Prescription not found');
  }
});

// @desc    Create a prescription (Doctor only)
// @route   POST /api/prescriptions
// @access  Private/Doctor
const createPrescription = asyncHandler(async (req, res) => {
  const { patientId, doctorId, issueDate, expiryDate, medicines, notes, secretNotes, prescriptionImage } = req.body;

  // console.log('Backend: createPrescription hit!');
  // console.log('Received req.body:', req.body);

  const patient = await Patient.findById(patientId);
  if (!patient) {
    res.status(404);
    throw new Error('Patient not found');
  }

  const doctor = await Doctor.findOne({ medicalRegistrationNumber: doctorId });
  if (!doctor) {
    res.status(404);
    throw new Error('Doctor not found');
  }

  // Ensure the logged-in user is the prescribing doctor or an admin
  if (req.user.role !== 'Admin' && doctor.user.toString() !== req.user._id.toString()) {
      res.status(403);
      throw new Error('Not authorized to create prescription for this doctor');
  }

  const prescription = new Prescription({
    patient: patient._id,
    doctor: doctor._id, // Use the MongoDB _id of the found doctor
    prescriptionId: `PRX-${Math.floor(100000 + Math.random() * 900000)}`,
    issueDate,
    expiryDate,
    medicines,
    notes,
    secretNotes,
    prescriptionImage,
  });

  // console.log('Before saving prescription:', prescription); // Add this line
  const createdPrescription = await prescription.save();
  // console.log('Prescription saved to DB:', createdPrescription);

  // Notify patient about new prescription
  if (patient.user) {
      const patientUser = await User.findById(patient.user);
      if (patientUser && patientUser.phoneNumber) {
          const msg = `Hello ${patientUser.name}, you have a new prescription from Dr. ${doctor.user.name}. View it in the HealthSphere app.`;
          sendSms(patientUser.phoneNumber, msg);
      }
  }

  await Notification.create({
      recipient: patient._id,
      onModel: 'Patient',
      title: 'New Prescription Issued',
      message: `Dr. ${doctor.user.name} has issued a new prescription for you.`, // Assuming doctor.user is populated
      category: 'Prescription',
      link: `/patient/prescriptions/${createdPrescription._id}`,
  });

  res.status(201).json(createdPrescription);
});

// @desc    Update a prescription (Admin/Doctor only)
// @route   PUT /api/prescriptions/:id
// @access  Private/Admin or Doctor
const updatePrescription = asyncHandler(async (req, res) => {
  const { issueDate, expiryDate, medicines, notes, secretNotes, prescriptionImage, status } = req.body;

  console.log(`Backend: PUT /api/prescriptions/${req.params.id} received.`);
  console.log('Backend: Request body:', req.body);
  console.log('Backend: Secret notes received in body:', secretNotes);

  const prescription = await Prescription.findById(req.params.id);

  if (prescription) {
    // Authorization: Only admin or the prescribing doctor can update
    const doctor = await Doctor.findById(prescription.doctor);
    if (req.user.role !== 'Admin' && doctor.user.toString() !== req.user._id.toString()) {
        res.status(403);
        throw new Error('Not authorized to update this prescription');
    }

    prescription.issueDate = issueDate || prescription.issueDate;
    prescription.expiryDate = expiryDate || prescription.expiryDate;
    prescription.medicines = medicines || prescription.medicines;
    prescription.notes = notes || prescription.notes;
    prescription.secretNotes = secretNotes; // Directly assign secretNotes, as it can be an empty string
    prescription.prescriptionImage = prescriptionImage || prescription.prescriptionImage;
    prescription.status = status || prescription.status;

    console.log("Backend: Prescription object before save in update:", prescription);
    const updatedPrescription = await prescription.save();
    console.log("Backend: Prescription object after save in update:", updatedPrescription);

    // Notify patient about prescription update
    const patient = await Patient.findById(updatedPrescription.patient);
    const doctorUser = await User.findById(doctor.user);

    if (patient && patient.user) {
        const patientUser = await User.findById(patient.user);
        if (patientUser && patientUser.phoneNumber) {
            const msg = `Hello ${patientUser.name}, your prescription from Dr. ${doctorUser.name} has been updated.`;
            sendSms(patientUser.phoneNumber, msg);
        }
    }
    await Notification.create({
        recipient: patient._id,
        onModel: 'Patient',
        title: 'Prescription Updated',
        message: `Your prescription from Dr. ${doctorUser.name} has been updated.`, // Assuming doctor.user is populated
        category: 'Prescription',
        link: `/patient/prescriptions/${updatedPrescription._id}`,
    });


    res.json(updatedPrescription);
  } else {
    res.status(404);
    throw new Error('Prescription not found');
  }
});

// @desc    Delete a prescription (Admin/Doctor only)
// @route   DELETE /api/prescriptions/:id
// @access  Private/Admin or Doctor
const deletePrescription = asyncHandler(async (req, res) => {
  const prescription = await Prescription.findById(req.params.id);

  if (prescription) {
    // Authorization: Only admin or the prescribing doctor can delete
    const doctor = await Doctor.findById(prescription.doctor);
    if (req.user.role !== 'Admin' && doctor.user.toString() !== req.user._id.toString()) {
        res.status(403);
        throw new Error('Not authorized to delete this prescription');
    }

    await prescription.deleteOne();
    res.json({ message: 'Prescription removed' });
  } else {
    res.status(404);
    throw new Error('Prescription not found');
  }
});

// @desc    Download Prescription as PDF
// @route   GET /api/prescriptions/:id/download-pdf
// @access  Private/Admin, Doctor, Patient
const downloadPrescriptionPdf = asyncHandler(async (req, res) => {
  const prescription = await Prescription.findById(req.params.id)
    .populate({ path: 'patient', select: 'patientId dob user', populate: { path: 'user', select: 'name _id' } })
    .populate({ path: 'doctor', select: 'specialty user', populate: { path: 'user', select: 'name _id' } })
    .populate('medicines.medicine', 'brandName genericName strength');

  if (!prescription) {
    res.status(404);
    throw new Error('Prescription not found');
  }

  // Authorization check (same as getPrescriptionById)
  console.log('downloadPrescriptionPdf: req.user._id:', req.user._id?.toString());
  console.log('downloadPrescriptionPdf: req.user.role:', req.user.role);
  console.log('downloadPrescriptionPdf: prescription.patient.user._id:', prescription.patient?.user?._id?.toString());
  console.log('downloadPrescriptionPdf: prescription.doctor.user._id:', prescription.doctor?.user?._id?.toString());
  const isAuthorized = req.user.role === 'Admin' ||
                       (prescription.patient && prescription.patient.user && prescription.patient.user._id.toString() === req.user._id.toString()) ||
                       (prescription.doctor && prescription.doctor.user && prescription.doctor.user._id.toString() === req.user._id.toString());

  if (!isAuthorized) {
      res.status(403);
      throw new Error('Not authorized to download this prescription');
  }

  const htmlContent = generatePrescriptionHtml(prescription);

  pdf.create(htmlContent, { format: 'Letter' }).toBuffer((err, buffer) => {
    if (err) {
      console.error('PDF creation error:', err);
      res.status(500).send('Error generating PDF');
      return;
    }

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=prescription-${prescription.prescriptionId}.pdf`);
    res.send(buffer);
  });
});

export { getPrescriptionsForDoctor, getPrescriptionById, createPrescription, updatePrescription, deletePrescription, getPatientPrescriptions, downloadPrescriptionPdf };
